// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MineCorp.Data;

#nullable disable

namespace MineCorp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MineCorp.Models.EmbeddedSystem", b =>
                {
                    b.Property<int>("SystemCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SystemCode"));

                    b.Property<decimal>("CH4")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CO")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("CO2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Dust")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Ethanol")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("H2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NH3")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NO2")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("SectorID")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SystemCode");

                    b.ToTable("EmbeddedSystems");
                });
#pragma warning restore 612, 618
        }
    }
}
